// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucplendwnjkgtodkbhnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjcGxlbmR3bmprZ3RvZGtiaG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MzYwNzIsImV4cCI6MjA1NDAxMjA3Mn0.ODiFFIAJuFyhrfAB8Hg6D8SBlvkS7reEKTAdJKoHaBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);